### PR TITLE
Build system, Continue on #3

### PR DESCRIPTION
**Pull request by stoivo**
Base on #3  and add build variants

### CODE REVIEW

**Comment by stoivo** [comment]
@tralamazza

**Comment by stoivo** [comment]
I have tested the mac and linux setup

**Comment by tralamazza** [comment]
We merge this instead of #3?

**Comment by stoivo** [comment]
yes, instead of #3. I based the my branch on #3 and added some future improvments.

**Comment by tralamazza** [comment]
Thank you

**Pull request merged**
